### ISSUE TITLE
create TUI with minimum navigation

### ISSUE THREAD

**Issue by ronaudinho** [ronaudinho/drt#2]

**Comment by RiskyFeryansyahP** [comment]
Hi @ronaudinho, do we have a design or layout for our terminal view in this project?

**Comment by ronaudinho** [comment]
![image](https://user-images.githubusercontent.com/10264710/236659473-c60a465f-d6b2-41a0-a72d-37643a4c7c98.png)

something like this for home page, and just replay viewer on enter/click on download/open button as well as ability to switch top/bottom (ignoring logo/name) panes should do.

**Comment by RiskyFeryansyahP** [comment]
> ![image](https://user-images.githubusercontent.com/10264710/236659473-c60a465f-d6b2-41a0-a72d-37643a4c7c98.png)
> 
> something like this for home page, and just replay viewer on enter/click on download/open button as well as ability to switch top/bottom (ignoring logo/name) panes should do.

Got it! Thanks!

**Comment by RiskyFeryansyahP** [comment]
Hi @ronaudinho, I'm currently working on this issue, but I have some questions regarding the TUI we're going to implement:
1. Because we're using `tcell` instead of `tview`, should we make each component ourselves? (e.g., input, list, box border, etc.)?
2. On the page there's a `download list.` Is the data for this list taken from a specific folder or elsewhere?
3. Or can we use `tcell` and `tview` in the same time? we use `tview` as our component so we didn't create it ourself

**Comment by ronaudinho** [comment]
for 1 and 3, I guess yes, but we can also use `tview` after all, now that I think of it, we might need multiple panes/boxes in replay viewer page.

for 2, I'm thinking  we can set default dir to something sane like `~/.config/drt/` (but this assumes non-windows system) or wherever dota default replayes folder is. for the moment, you can just fill it with dummy list.
